name: Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore -c Release

    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Publish API
      uses: ./.github/actions/template_pack-dotnet
      with:
        projectFile: "src/UpBlazor.WebAPI/UpBlazor.WebAPI.csproj"
        outputFolder: "./API"

    - name: Publish UI
      uses: ./.github/actions/template_pack-dotnet
      with:
        projectFile: "src/UpBlazor.WebUI/UpBlazor.WebUI.csproj"
        outputFolder: "./UI"

    - name: Deploy API
      id: deploy-api
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'upblazor-webapi'
        slot-name: 'Production'
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_1A26B43F89B34C58ADF4A707F0D8B3E8 }}
        package: "./publish/API"

    - name: Deploy UI
      id: deploy-ui
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_NICE_GLACIER_04F65F810 }}
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        action: "upload"
        app_location: "./publish/UI"
        skip_app_build: true
